### ISSUE TITLE
Add the Travis CI app to the organization

### ISSUE THREAD

**Issue by oliverklee** [phpList/core#298]
Travis CI has deprecated their services, i.e., the Travis CI service as well. Instead, GitHub Apps and webhooks should be used.

@samtuke, could you please grant the Travis CI app access to the GitHub repo? Thanks!

https://github.com/marketplace/travis-ci

**Comment by samtuke** [comment]
Thank Oliver. This should now be done. Please check.

**Comment by oliverklee** [comment]
Looks good. Thanks!
