### ISSUE TITLE
Initializing database error

### ISSUE THREAD

**Issue by salsarapidoman** [phpList/core#326]
### Short problem description
when installing on php8, the link to 'Initialize database' was not present. When I changed to php7.4 everything ok.

### System configuration
Cpanel shared hosting package
3.6.2
#### PHP and Composer version
error with php8 (files uploaded via ftp not composer)

I hope this helps as this is a wonderful program :)

**Comment by Fenn-CS** [comment]
Hi @salsarapidoman thanks for pointing that out, `phplist/core` does not yet have full support for `php8` the currently recommended versions to use are `7.2, 7.3 and 7.4`.

We would be bringing in support for `php8` in the nearest future. 😃

**Comment by michield** [comment]
hi @salsarapidoman. This is not the correct project for that report. You are looking for @phpList/phplist3 

But also, you can ask questions like this on the forums https://discuss.phplist.org

but also, we notified everyone that PHP8 is not yet supported, see https://www.phplist.org/newslist/phplist-3-6-2-release-notes/
